### PR TITLE
Re-add accidentally removed constant in RecordBatch

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**
Fixes a bug in unrelease code in v5.x.x.

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
Actually, this needs to be applied to the `v4.6.x` since the existing code is broken: https://github.com/sociomantic-tsunami/swarm/blob/f337984496e0f08d08f4be5997b4272d9c0e0dab/src/swarm/util/RecordBatcher.d#L446

This is the commit that broke it: https://github.com/sociomantic-tsunami/swarm/commit/4a3b231848cc09957e32276c060196cdf4e8da50#diff-2e8543d3803639dbe31ba37f78932691

**Comment by gavin-norman-sociomantic** [comment]
Mm, my reading of the branch history doesn't agree. It does look like this needs to be applied to v4.x.x, though (not v5.x.x).

**Comment by gavin-norman-sociomantic** [comment]
Yeah, at v4.6.2 (b632c1a16fa4a3763f3e5354c7fb60186777ff7a), `RecordBatchBase` still exists: https://github.com/sociomantic-tsunami/swarm/blob/b632c1a16fa4a3763f3e5354c7fb60186777ff7a/src/swarm/util/RecordBatcher.d#L36

**Comment by nemanja-boric-sociomantic** [comment]
Yes, sorry, it's the `v4.x.x` (this is where I found the error.)

**Comment by gavin-norman-sociomantic** [comment]
Rebased on v4.x.x.

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by nemanja-boric-sociomantic** [comment]
Very interesting D2 failure that I can't explain for this diff?

**Comment by gavin-norman-sociomantic** [comment]
Weird. Seemingly unrelated visibility issues.

**Comment by nemanja-boric-sociomantic** [comment]
Yeah, it's travis targeting the v5.x.x branch.

**Comment by gavin-norman-sociomantic** [comment]
test this please travis

**Pull request merged**
