### PR TITLE
Merge v4.x.x -> v5.x.x

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
What's wrong, Travis?
>Fetched in submodule path 'submodules/ocean', but it did not contain b11b21df6e264d858d85aa1bbcc4b09f866b27e1. Direct fetching of that commit failed.

But it does exist: https://github.com/sociomantic-tsunami/ocean/commit/b11b21df6e264d858d85aa1bbcc4b09f866b27e1

**Comment by mihails-strasuns-sociomantic** [comment]
NB: we don't merge changes into in-development major, instead it is being rebased on top of current HEAD of previous major.

**Comment by gavin-norman-sociomantic** [comment]
Ok I can try that.

**Comment by gavin-norman-sociomantic** [comment]
(Though I suspect the Travis failure will be the same.)

**Pull request closed without merging**
