### PR TITLE
Update LibFeatures.d

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**

### CODE REVIEW

**Comment by mathias-lang-sociomantic** [comment]
We had this discussion with @mihails-strasuns-sociomantic before, and adding a missing entry in LibFeatures in a patch release is not such a good idea.

**Comment by gavin-norman-sociomantic** [comment]
Oh yeah? Why was that?

**Comment by mathias-lang-sociomantic** [comment]
https://github.com/sociomantic-tsunami/ocean/pull/284#issuecomment-334401366

**Comment by gavin-norman-sociomantic** [comment]
I see. Damn. Another vote for the importance of https://github.com/sociomantic-tsunami/neptune/issues/48 ;)

**Comment by gavin-norman-sociomantic** [comment]
Updated: based on v4.x.x; also adds v4.5.0.

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Pull request merged**
