### PR TITLE
Remove last usage of Layout_Tango

### PR DESCRIPTION
**Pull request by mathias-lang-sociomantic**
Trivial since it's in unittest

### CODE REVIEW

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by gavin-norman-sociomantic** [comment]
Is this needed in v3.x.x? We've been in the habit of only maintaining v3.x.x with bug fixes. It doesn't seem worth making a minor release on v3.x.x just for this change.

**Comment by mihails-strasuns-sociomantic** [comment]
AFAICS there is not a single project using v3.x.x swarm now so maybe we can just move the branch out of support prematurely?

**Comment by gavin-norman-sociomantic** [comment]
Oh yeah, excellent point! (Wow.)

**Comment by gavin-norman-sociomantic** [comment]
swarm v3.x.x only has 2 weeks' life left anyway.

**Comment by mathias-lang-sociomantic** [comment]
> Is this needed in v3.x.x? We've been in the habit of only maintaining v3.x.x with bug fixes. It doesn't seem worth making a minor release on v3.x.x just for this change.

So not actually following the neptune guide authored by your team :grumpy:
Rebased on v4.x.x and changed target branch.

**Comment by gavin-norman-sociomantic** [comment]
Haha yeah... swarm is a little bit different, in that it's mostly an internal library, not something that users need to interact with directly any more.

**Review by gavin-norman-sociomantic — APPROVED** [review]

**Comment by mihails-strasuns-sociomantic** [comment]
> So not actually following the neptune guide authored by your team

I have heard rumors that @gavin-norman-sociomantic also refused tea once.

**Pull request merged**
