### PR TITLE
Fix merge error in previous commit

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**

### CODE REVIEW

**Comment by nemanja-boric-sociomantic** [comment]
```
./src/swarm/neo/node/ConnectionHandler.d(484): vgc: using closure causes GC allocation
```

**Comment by gavin-norman-sociomantic** [comment]
Must be another merge error or a closure that was present in v5.0.x.

**Comment by nemanja-boric-sociomantic** [comment]
Yeah, I think this might be just the closure already present in v5.0.x.

**Comment by nemanja-boric-sociomantic** [comment]
Fix:

```diff
-            this.shared_params.get_resource_acquirer(
+            scope handle_request =
                 ( Object request_resources )
                 {
                     auto rq_handler = this.emplace!(IRequestHandler)
@@ -520,8 +520,9 @@ class ConnectionHandler : IConnectionHandler
                     this.sendSupportedStatus(connection,
                         SupportedStatus.RequestSupported);
                     rq_handler.postSupportedCodeSent();
-                }
-            );
+                };
+
+            this.shared_params.get_resource_acquirer(handle_request);
```

**Comment by gavin-norman-sociomantic** [comment]
Pushed extra commit.

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Pull request merged**
