### PR TITLE
travis: Use beaver to build the project and remove trusty

### PR DESCRIPTION
**Pull request by leandro-lucarella-sociomantic**
This also introduces matrix builds to test D1/D2 and uses specific DMD versions.

This is a WIP, like https://github.com/sociomantic-tsunami/ocean/pull/209, based on my fork for testing.

It will need to be updated when a new beaver release is out.

### CODE REVIEW

**Comment by leandro-lucarella-sociomantic** [comment]
:green_heart:

**Review by gavin-norman-sociomantic — APPROVED** [review]
From my very minimal experience with beavery things, it looks conceivable that this is correct :D

**Comment by gavin-norman-sociomantic** [comment]
What branch should this be against? It's based on v3.3.x, but is labelled as a feature, not a bug fix.

**Comment by leandro-lucarella-sociomantic** [comment]
Well, I think we are missing labels for infra work (like we have in ocean, a `part-infrastructure` label). It is an improvement in CI. It doesn't make sense to use semver nomenclature here because these changes are not user-facing at all.

**Comment by leandro-lucarella-sociomantic** [comment]
BTW, I think improvements to the CI should be generally done to the "lowest common denominator", so it is eventually merged to all supported branches.

**Comment by gavin-norman-sociomantic** [comment]
Makes sense.

v3.3.4 is ready to be released. Is this ready to be merged or should we move it to v3.3.5?

**Comment by leandro-lucarella-sociomantic** [comment]
Not ready because there is no beaver release yet. Feel free to move to the next point release.

**Comment by leandro-lucarella-sociomantic** [comment]
Update with the latest full automation beaver PR and :green_heart:!

Still will need to release beaver before merging.

**Comment by leandro-lucarella-sociomantic** [comment]
(re-triggered the test to remove the `after-success` that was left calling a non-existent script)

**Comment by gavin-norman-sociomantic** [comment]
Is this still WIP?

**Comment by leandro-lucarella-sociomantic** [comment]
Sort of, same as before, we still need to release beaver for this to be final. I will let you know when it is ready for the final review.

**Comment by leandro-lucarella-sociomantic** [comment]
Now it's ready.

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Review by mihails-strasuns-sociomantic — APPROVED** [review]

**Pull request merged**
