### PR TITLE
Replace all usages of `Const!` and `Immut!`

### PR DESCRIPTION
**Pull request by jens-mueller-sociomantic**
With this change all usage of the templates `Const` and `Immut` is replaced by
their appropriate D2 builtins.
The code base is now free of `Const`, `Immut` and `Inout`. For `Inout` no
changes had to be made because it is not used `Inout`.

Fixes sociomantic-tsunami/swarm#406.

### CODE REVIEW

**Review by don-clugston-sociomantic — APPROVED** [review]
LGTM

**Comment by jens-mueller-sociomantic** [comment]
Just to make sure: Am I targeting the right branch?

**Comment by jens-mueller-sociomantic** [comment]
Shouldn't I target `v5.x.x`?

**Comment by jens-mueller-sociomantic** [comment]
Just checked: I think v6.x.x is fine because this should be when D1 support was dropped.

**Comment by jens-mueller-sociomantic** [comment]
How many approvals do I need to merge it? I remember with some libraries you need at least two.

**Review by alaksiej-stankievicx-dunnhumby — APPROVED** [review]

**Pull request merged**
