### PR TITLE
Automatic D2 tag release

### PR DESCRIPTION
**Pull request by mihails-strasuns-sociomantic**
Copied from ocean. Will require configuring same secret env variables for swarm
repo.

### CODE REVIEW

**Review by leandro-lucarella-sociomantic — APPROVED** [review]

**Comment by mihails-strasuns-sociomantic** [comment]
@leandro-lucarella-sociomantic can you configure required env vars for swarm?

**Comment by leandro-lucarella-sociomantic** [comment]
Done. Also for all other swarm related tsunami library repos and turtle.

**Comment by gavin-norman-sociomantic** [comment]
@mihails-strasuns-sociomantic could you add Fixes #32 to the commit message?

**Comment by mihails-strasuns-sociomantic** [comment]
Done

**Comment by gavin-norman-sociomantic** [comment]
Is everything ready to merge this now?

**Comment by mihails-strasuns-sociomantic** [comment]
Yes, next release should be converted as soon as you merge this.

**Comment by gavin-norman-sociomantic** [comment]
Excellent, thanks!

**Pull request merged**
