### PR TITLE
Fix some implicit string concatenations

### PR DESCRIPTION
**Pull request by joseph-wakeling-sociomantic**
Implicit string concatenation is deprecated in D2, so this should save some compiler warnings in future.

### CODE REVIEW

**Comment by joseph-wakeling-sociomantic** [comment]
Found a few more, so added a couple of extra patches accordingly.

**Comment by gavin-norman-sociomantic** [comment]
Can you rebase this? (A travis fix was just pushed into v4.x.x.)

**Comment by nemanja-boric-sociomantic** [comment]
I've just restared the build. Since there are no commits and Travis will test the merge commit, this should be good to go.

**Comment by gavin-norman-sociomantic** [comment]
Ah ok.

**Review by nemanja-boric-sociomantic — APPROVED** [review]

**Comment by joseph-wakeling-sociomantic** [comment]
For the record, I missed the following modules:

```
src/swarm/util/node/log/Stats.d
src/swarm/node/connection/ConnectionHandler.d
src/swarm/neo/client/mixins/RequestCore.d
src/swarm/neo/client/Connection.d
src/swarm/neo/client/NotifierTypes.d
src/swarm/client/plugins/NodeDeactivator.d
```

I'll try to do a follow-up set of patches some time to cover all of these.

**Pull request merged**
