### PR TITLE
Add DelayedSuspender multi-fiber request helper

### PR DESCRIPTION
**Pull request by gavin-norman-sociomantic**

### CODE REVIEW

**Comment by gavin-norman-sociomantic** [comment]
Required by #3.

**Comment by gavin-norman-sociomantic** [comment]
Based on #22. Blocked until that PR is merged.

**Comment by gavin-norman-sociomantic** [comment]
Prerequisites merged. Unblocked.

**Review by nemanja-boric-sociomantic — APPROVED** [review]
Very nice and clear!

**Pull request merged**
